spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost/forumhub
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true